<?php

/**
 * This field lets you preview how the page will be previewed in search results.
 *
 * <code>
 * new SeoPreviewField (
 *    $name = "seopreviewfield",
 *    $title = "title",
 *    $description = "description",
 *    $link = "link"
 * )
 * </code>
 * 
 * @package seo
 */
class SeoPreviewField extends LiteralField {
	
	/**
	 * @var string
	 */
	protected $title;	
	
	/**
	 * @var string
	 */
	protected $description;	

	/**
	 * @var string
	 */
	protected $link;		
	
	/**
	 * Create the SEO preview field
	 * 
	 * @param string $name
	 */
	public function __construct($name, $title, $description, $link) 
	{
		$this->title = $title;
		$this->description = $description;
		$this->link = $link;
		parent::__construct($name, $this->getContent());
	}
	
	/**
	 * Get content
	 * 
	 * @return string
	 */
	public function getContent()
	{
		return Controller::curr()->customise(array(
			"SeoTitle" => $this->getSeoTitle(),
			"SeoDescription" => $this->getSeoDescription(),
			"SeoLink" => $this->getSeoLink(),
			"DefaultDescription" => $this->getDefaultDescription()
		))->renderWith('SeoPreviewField');
	}	
	
	/**
	 * Get title
	 * 
	 * @return string
	 */
	public function getSeoTitle() 
	{
		return $this->title;
	}
	
	/**
	 * Get link
	 * 
	 * @return string
	 */
	public function getSeoLink() 
	{
		return $this->link;
	}	
	
	/**
	 * Get description
	 * 
	 * @return string
	 */
	public function getSeoDescription() 
	{
		return empty($this->description) ? $this->getDefaultDescription() : $this->description;
	}
	
	/**
	 * Get the default description
	 * 
	 * @return string
	 */
	public function getDefaultDescription() {
		return "Meta description is generated by Google.";
	}
		
}