---
Name: 'seoextensions'
---
Page:
  extensions:
    - SeoSiteTreeExtension
SiteConfig:
  extensions:
    - SeoSiteConfigExtension
# Example of how to exclude extra page types from showing the SEO tab:
# SeoObjectExtension:
#   excluded_page_types:
#     - 'SomePage'

